"""Source and EvidenceChunk persistence models."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING

from sqlalchemy import JSON, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, CreatedAtMixin, UUIDPKMixin

if TYPE_CHECKING:
    from app.db.models.fact import ExtractedFact
    from app.db.models.research_task import ResearchTask


class SourceType(str, Enum):
    ANNUAL_REPORT = "annual_report"
    ANNOUNCEMENT = "announcement"
    OFFICIAL_PDF = "official_pdf"
    OFFICIAL_DISCLOSURE_PAGE = "official_disclosure_page"
    NEWS = "news"
    OFFICIAL_WEBSITE = "official_website"
    GOVERNMENT = "government"
    PATENT = "patent"
    HIRING = "hiring"
    OTHER = "other"


class Source(UUIDPKMixin, CreatedAtMixin, Base):
    __tablename__ = "sources"

    task_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("research_tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    url: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    source_type: Mapped[SourceType] = mapped_column(String(32), nullable=False)
    published_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    retrieved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )
    raw_content: Mapped[str] = mapped_column(Text, nullable=False)
    # Heuristic score used by source sorting and evidence gates.
    credibility_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    source_metadata: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    task: Mapped[ResearchTask] = relationship(back_populates="sources")
    chunks: Mapped[list[EvidenceChunk]] = relationship(
        back_populates="source",
        cascade="all, delete-orphan",
        order_by="EvidenceChunk.chunk_index",
    )
    facts: Mapped[list[ExtractedFact]] = relationship(back_populates="source")


class EvidenceChunk(UUIDPKMixin, CreatedAtMixin, Base):
    """资料切片 —— RAG 的最小检索单元。

    注意：
    - SQLAlchemy 中 ``metadata`` 是 ``Base.metadata`` 的保留名，
      因此业务字段命名为 ``chunk_metadata``。
    - ``embedding_id`` may be generated by the configured embedding provider.
    """

    __tablename__ = "evidence_chunks"

    source_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("sources.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    task_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("research_tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)
    # 数据库列名使用 chunk_metadata，与历史开发库 `data/dev.db` 及 create_all 一致，避免
    # 将列重命名为 metadata 后旧库与 ORM 不一致。对外 API/Schema 仍用字段名
    # ``metadata``（见 EvidenceChunkRead 的 validation_alias）。
    chunk_metadata: Mapped[dict | None] = mapped_column("chunk_metadata", JSON, nullable=True)
    embedding_id: Mapped[str | None] = mapped_column(String(128), nullable=True)

    source: Mapped[Source] = relationship(back_populates="chunks")
    task: Mapped[ResearchTask] = relationship(back_populates="evidence_chunks")
    facts: Mapped[list[ExtractedFact]] = relationship(back_populates="chunk")
