"""报告与答题链路的展示/截断上限（集中配置）。"""

from __future__ import annotations

# 选题与正文
MAX_PRIMARY_FACTS = 8
MAX_CONTEXT_FACTS = 4
MAX_CORE_FINDINGS_DISPLAY = 10
MAX_OPTIONAL_CONTEXT_DISPLAY = 6
MAX_COMPOSER_FACTS_IN_PARAGRAPH = 4
MAX_TREND_FACTS_IN_PARAGRAPH = 5

# 附录与歧义
MAX_AMBIGUITY_GROUPS = 6
MAX_AMBIGUITY_VALUES_PER_GROUP = 4
MAX_CONFLICTED_APPENDIX = 4
MAX_OUTDATED_APPENDIX = 3
MAX_REJECTED_APPENDIX = 3

# 追问
MAX_FOLLOWUP_CITATIONS = 8
FALLBACK_REPORT_BRIEF_LIMIT = 220

# 校验冲突条数达到该阈值时，总结段追加利润口径提示
VERIFICATION_CONFLICT_NOTE_THRESHOLD = 8
